[Engine]

# 将棋ソフトの表示名です。 後ろにバージョン番号が付くなどの加工があることがあります。
Name = "Kifuwaragyoku"

# 将棋ソフトの制作者名です。
Author = "Satoshi TAKAHASHI"

[Resources]

# `Engine01_Config` は `Data` に名称変更。
# `Engine01_Logs` は `Logs` に名称変更。

DataDirectory = "./Data/"
LogDirectory = "../Logs"
ImgGkLogDirectory = "./Data/img/gkLog/"
KifuTreeLogDirectory = "../Logs/_log_KifuTreeLog/"
ImgMobilityDirectory = "./Data/img/mobility/"
ImgKomaDirectory = "./Data/img/koma/"
# HTMLに埋め込むパスは、末尾の / の有無の調整がむずかしい☆（＾～＾）　プログラム側で一手間かけること☆（＾～＾）
# path = path.EndsWith("/") ? path.Substring(0, path.Length - 1) : path;
ImgDirectory = "./Data/img"

Michi187 = "./Data/data_michi187.csv"
Haiyaku185 = "./Data/data_haiyaku185_UTF-8.csv"
InputForcePromotion = "./Data/data_forcePromotion_UTF-8.csv"
OutputForcePromotion = "../Logs/#強制転成表.log.html"
InputSyuruiToHaiyaku = "./Data/data_syuruiToHaiyaku.csv"
OutputSyuruiToHaiyaku = "../Logs/#配役転換表.log.html"
Shogiban01Widgets = "./Data/data_widgets_01_shogiban.csv"
Console02Widgets = "./Data/data_widgets_02_console.csv"
Vs03Widgets = "./Data/data_widgets_03_vs.csv"

DataSetteiVsCsv = "./Data/data_settei_vs.csv"
AimsDataSetteiXml = "./CSharp/Engine01_Config/data_settei.xml"
DataScoreLua = "./Data/lua/KifuWarabe/data_score.lua"
NarabeDataGuiLua = "./Data/lua/KifuNarabe/data_gui.lua"
DataSetteiXml = "./Data/data_settei.xml"

MichiHyoLogHtml = "../Logs/#道表.log.html"

# テキストファイル

LogDaseMeirei = "../Logs/#ログ出せ命令.log"
DataStyleText = "./Data/data_style.txt"
HaiyakuTenkanhyoLoad1DataOnly = "../Logs/#配役転換表Load(1)_データ行のみ.log"
HaiyakuTenkanhyoLoad2 = "../Logs/#配役転換表Load(2).log"

# 画像

# var profilePath = System.Configuration.ConfigurationManager.AppSettings["Profile"];
# var toml = Toml.ReadFile(Path.Combine(profilePath, "Engine.toml"));
# Path.Combine(profilePath, toml.Get<TomlTable>("Resources").Get<string>("xxxxxxxxxxxxxxxx"))

LearningPositionLogPng = "../Logs/#学習局面.log.png"
LearningPositionLogPngFilename = "#学習局面.log.png"
ChokkinNoSasitePngFilename = "#直近の指し手.log.png"
Koma1PngFilename = "koma1.png"
Suji1PngFilename = "suji1.png"

N1PngFilename = "1.png" # 出力ファイル
N2PngFilename = "2.png" # 駒画像へのパス。
N3PngFilename = "3.png" # 数字・小

# Fv

Fv00Komawari = "./Data/fv/fv_00_Komawari.csv"
# Fv00Scale = "./Data/fv/fv_00_Scale.csv"
# Fv01KK = "./Data/fv_01_KK.csv"
# Fv2Sample = "./Data/fv_2(sample).csv"

Fv00ScaleInFvDir = "fv_00_Scale.csv"
Fv01KKInFvDir = "fv_01_KK.csv"

Fv02n1pKPInFvDir = "fv_02_1pKP.csv"
Fv03n2pKPInFvDir = "fv_03_2pKP.csv"

Fv04PP1pInFvDir = "fv_04_PP_1p____Fu__.csv"
Fv05PP1pInFvDir = "fv_05_PP_1p____Kyo_.csv"
Fv06pp1pInFvDir = "fv_06_pp_1p____Kei_.csv"
Fv07pp1pInFvDir = "fv_07_pp_1p____Gin_.csv"
Fv08pp1pInFvDir = "fv_08_pp_1p____Kin_.csv"
Fv09pp1pInFvDir = "fv_09_pp_1p____Hi__.csv"
Fv10pp1pInFvDir = "fv_10_pp_1p____Kaku.csv"
Fv18pp2pInFvDir = "fv_18_pp_2p____Fu__.csv"
Fv19pp2pInFvDir = "fv_19_pp_2p____Kyo_.csv"
Fv20pp2pInFvDir = "fv_20_pp_2p____Kei_.csv"
Fv21pp2pInFvDir = "fv_21_pp_2p____Gin_.csv"
Fv22pp2pInFvDir = "fv_22_pp_2p____Kin_.csv"
Fv23pp2pInFvDir = "fv_23_pp_2p____Hi__.csv"
Fv24pp2pInFvDir = "fv_24_pp_2p____Kaku.csv"

Fv11PP1pInFvDir = "fv_11_PP_1pMotiFu__.csv"
Fv25pp2pInFvDir = "fv_25_pp_2pMotiFu__.csv"

Fv12PP1pInFvDir = "fv_12_PP_1pMotiKyo_.csv"
Fv13pp1pInFvDir = "fv_13_pp_1pMotiKei_.csv"
Fv14pp1pInFvDir = "fv_14_pp_1pMotiGin_.csv"
Fv15pp1pInFvDir = "fv_15_pp_1pMotiKin_.csv"
Fv26pp2pInFvDir = "fv_26_pp_2pMotiKyo_.csv"
Fv27pp2pInFvDir = "fv_27_pp_2pMotiKei_.csv"
Fv28pp2pInFvDir = "fv_28_pp_2pMotiGin_.csv"
Fv29pp2pInFvDir = "fv_29_pp_2pMotiKin_.csv"

Fv16pp1pInFvDir = "fv_16_pp_1pMotiHi__.csv"
Fv17pp1pInFvDir = "fv_17_pp_1pMotiKaku.csv"
Fv30pp2pInFvDir = "fv_30_pp_2pMotiHi__.csv"
Fv31pp2pInFvDir = "fv_31_pp_2pMotiKaku.csv"

[Logs]

N01ProcessNoneErrorLog = "#エラー.log"
N02PeocessNoneSennititeLog = "#Default_千日手判定.log"
N03ProcessServerDefaultLog = "#ｻｰﾊﾞｰ_ﾃﾞﾌｫﾙﾄ.log"
N04ProcessServerNetworkAsyncLog = "#ｻｰﾊﾞｰ_非同期通信.log"
N05ProcessGuiDefaultLog = "#CsharpGUI_ﾃﾞﾌｫﾙﾄ.log"
N06ProcessGuiKifuYomitoriLog = "#CsharpGUI_棋譜読取.log"
N07ProcessGuiNetworkLog = "#CsharpGUI_通信.log"
N08ProcessGuiPaintLog = "#CsharpGUI_ﾍﾟｲﾝﾄ.log"
N09ProcessGuiSennititeLog = "#CsharpGui_千日手判定.log"
N10ProcessAimsDefaultLog = "#AIMS対応用_ﾃﾞﾌｫﾙﾄ.log"
N11ProcessEngineDefaultLog = "#ｴﾝｼﾞﾝ_ﾃﾞﾌｫﾙﾄ.log"
N12ProcessEngineNetworkLog = "#ｴﾝｼﾞﾝ_通信.log"
N13ProcessEngineSennititeLog = "#ｴﾝｼﾞﾝ_千日手判定.log"
N14ProcessTestProgramDefaultLog = "#テスト・プログラム用（汎用）.log"
N15ProcessLearnerDefaultLog = "#棋譜学習ソフト用.log"
N16ProcessSpeedTestKeisokuLog = "#スピード計測ソフト用.log"
N17ProcessUnitTestDefaultLog = "#ユニットテスト用.log"

KyouseiTenseiDebug = "#強制転成デバッグ.log"

Trace = "Trace.log"
Debug = "Debug.log"
Info = "Info.log"
Notice = "Notice.log"
Warn = "Warn.log"
Error = "Error.log"
Fatal = "Fatal.log"
